[package]
name = "round-trip"
version = "0.1.0"
authors = ["Eric Harris-Braun <eric@harris-braun.com>, Nicolas Luck <nicolas@lucksus.eu>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
serde="1"
serde_derive="1"
holochain_wasm_utils = { path = "../../../wasm_utils"}