[package]
name = "debug"
version = "0.1.0"
authors = ["Nicolas Luck <nicolas@lucksus.eu>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
holochain_wasm_utils = { path = "../../../../wasm_utils"}
