[package]
name = "holochain_agent"
version = "0.1.0"
authors = ["Eric Harris-Braun <eric@harris-braun.com>"]

[dependencies]
holochain_core_types = { path = "../core_types" }
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
